version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    groups:
      actions-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: quarterly
    groups:
      pnpm-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
